### ISSUE TITLE
Impact of CurrentCulture on acceptance tests

### ISSUE THREAD

**Issue by acinep** [jburzynski/TypeGen#100]
The GeneratorAcceptanceTests currently fail for me because evidently my CurrentCulture is different from the one used to generate the Expected files.  This manifests in the ExtendedPrimitivesClass - the DateTime/Offset strings are different...

Happy to do a PR to correct this - but would appreciate some guidance on your preferred approach

- Explicitly set the CurrentCulture in the test itself (if so, which culture?)
- Alter the generator to output a fixed datetime string irrespective of culture (e.g. ISO8601)
- Allow control of the format via the generator spec/attributes

thanks!

**Comment by jburzynski** [comment]
Hi, sorry for the quite late response,

Thank for reporting this issue,

If I were to fix this issue, I'd go with the 2nd billet point (fixed datetime string, iso8601 seems ok).

Lately I haven't had a lot of time for this project and I think I need some time "off", so I won't be doing much work on it in the near future.

You can create your own NuGet package from the source if you'd like to use your code (there's a guide in the main readme file).
