### ISSUE TITLE
<custom-body> inside enum doesn't stay after regenarate

### ISSUE THREAD

**Issue by plmonnier** [jburzynski/TypeGen#107]
Hello, 
 I would like to add a value to my enum generated with TypeGen. Something like : 
export enum TextCustomEnum{
    Txt1 = 0,
 // <custom-body>
    Txt2 = 1,
 // </custom-body>
}

But the custom part disappear after regenarate
Thanks !

**Comment by jburzynski** [comment]
Fixed in 4.1.1.
