### ISSUE TITLE
Throw Error to console

### ISSUE THREAD

**Issue by vladkasianenko** [jburzynski/TypeGen#114]
Error is now thrown and as a result pipeline finished successfully.
![image](https://user-images.githubusercontent.com/14053728/104023940-09d38480-51cb-11eb-8d69-2ef2447600d4.png)

I guess it should be red and exited with error code.

**Comment by jburzynski** [comment]
Fixed in 4.1.1. Currently it returns an exit code '1' on failure and '0' on success.
