### ISSUE TITLE
I'd like to maintain this repository

### ISSUE THREAD

**Issue by fusionat** [jburzynski/TypeGen#118]
Hi

How can I help to maintain this repository? 
I would like to add .net 5, net 6 and fix several issues.

**Comment by jburzynski** [comment]
Hi,

thanks for offering to help,

I sent you an invitation as a collaborator, which means you'd be able to make changes in the code (commit, merge pull requests etc.).

Also, if you'd like, feel free to upload any new packages to [NuGet](https://www.nuget.org/packages/TypeGen).

In case of any problems/questions you can contact me on my e-mail: jburzyn@gmail.com

Thanks,

Jacek

**Comment by fusionat** [comment]
Fixed
