### ISSUE TITLE
v2.5.2 is a breaking change!

### ISSUE THREAD

**Issue by richbrowne-openfin** [jburzynski/TypeGen#123]
In version 2.5.2 TypeGen has moved to .NET 6, this is a breaking change and so the version number should be 3.0.0 to signify a major update with potentially breaking changes (as per [semver](https://semver.org/)) and is certainly not a patch update!

**Comment by jburzynski** [comment]
Thanks for pointing this out, a new version 3.0.0 was released (it's the same as 2.5.2, but only has a different version).
