### ISSUE TITLE
Add possibility to redefine class name s

### ISSUE THREAD

**Issue by haga-rak** [jburzynski/TypeGen#125]
It could be a good addon to give the ability to change the outputed class/interface name.  Just like **TsMemberNameAttribute** but at class/interface level. 

Backend C# code may contains suffix like DTO, ViewModels which are completely redundant at Typescript level. 

Eg: 

```
[ExportTsInterface(Name="Dog")]
public class DogViewModel {
...
```

**Comment by jburzynski** [comment]
This particular use case should be covered by [converters](https://typegen.readthedocs.io/en/latest/converters.html). At the bottom of this documentation page there is even an example that solves one of the mentioned problems (stripping the DTO suffix, by using a _StripDtoConverter_). So I'll consider this issue as solved at the moment.
