### ISSUE TITLE
Supporting comments?

### ISSUE THREAD

**Issue by jimbobsmith** [jburzynski/TypeGen#130]
It'd be nice to have the c# property comments generated to the ts file property comments

**Comment by bigbadwolf88888** [comment]
Agree, comments would be very helpful.

**Comment by jburzynski** [comment]
This is added in version 4.4.0. TypeGen gets the comments from the xmldoc file for the assembly. This will only work if the xmldoc file is in the same directory as the assembly and has the same name (except the file extension).
