### ISSUE TITLE
Feature: Parsing complex custom types

### ISSUE THREAD

**Issue by daveriedstra** [jburzynski/TypeGen#15]
This annotation
```
[TsType("MyType[]", "./my-type")]
```
currently results in this incorrect import
```
import { MyType[] } from "./my-type";
```
The results are similar with `MyType?`. The workaround is to manually import the type in the .ts file with a custom header and not specify an import in `TsType`. Since that's simple enough to do, this issue is a feature request for parsing in the TsType attribute.

**Comment by jburzynski** [comment]
Should be fixed in 1.5.11. Fixed for arrays [], generic types <> and "undefined-able" ?
