### ISSUE TITLE
Make "bin" directory configurable

### ISSUE THREAD

**Issue by aduggleby** [jburzynski/TypeGen#153]
dotnet build allows you to specify the output directory (this is the case for example in default GitHub action / Azure CI templates) using the --output parameter, e.g.:

`dotnet build --configuration Release --output ./bin`

If you have dotnet-typegen as a postbuild step then this fails as the CLI has "bin" hard-coded here: 

https://github.com/jburzynski/TypeGen/blob/a544a575cc823fcd675c07adf20426b52c9ab34e/src/TypeGen/TypeGen.Cli/Business/ConfigProvider.cs#L111

Maybe this could be added as a configurable parameter in the future to support this case. The workaround for now is just to not change the output directory (or change the default workflow script to not change it).

**Comment by miltonhowe** [comment]
👍 I am running in to this problem as well. My project, a legacy .Net Framework 4.8  project, uses
`..\..\..\artifactsxyzProject` as the Build destination and I am struggling to configure the TypeGen tools to find the assembly.

**Comment by jburzynski** [comment]
Fixed in 4.1.1. There is a new config parameter `projectOutputFolder` to specify the output folder (it's set to "bin" by default).
