### ISSUE TITLE
Type 'TypeScriptGenSpec' not found in TypeGen.Core or any of the assemblies

### ISSUE THREAD

**Issue by MeikelLP** [jburzynski/TypeGen#158]
I noticed that some of my coworkers had issues with TypeGen. After reading some logs (via `--verbose`) we noticed that the CLI (`4.1.1`) tries to read the first build directory which was `/bin/Debug/net5.0/OurProject.dll`

But we moved to .NET 6 some time ago and just some old co workers have these directories still lying around.

The issue is resolved by just deleting the `net5.0` directory

**Comment by jburzynski** [comment]
Thanks for reporting this issue and sharing the solution - I'm closing the issue, as it has been solved.
