### ISSUE TITLE
Typescript-only members

### ISSUE THREAD

**Issue by mispencer** [jburzynski/TypeGen#166]
I would like to be able to create members in the generated TS classes that don't exist in the source C# classes.

Rationale: I am using this to type JSON created by my service, however the JSON generated does not exactly match the source C# classes.

Possible Workaround: Custom typescript that references the generate TS files
Problems: Only suitable for top-level types. Changes to types nested in other types required customized all containing types and their containing types all the way up the tree. Potentially very many custom types if nested within many top-level types with many levels of nesting.

Possible Workaround: <custom-body>
Problem: Requires checking in generated TS files. Generated files containing manual changes is unexpected and easily missable.

**Comment by jburzynski** [comment]
Implemented in version 4.5.0 by merging #167
