### ISSUE TITLE
Overriding OnAfterGeneration does not work,

### ISSUE THREAD

**Issue by stealthAngel** [jburzynski/TypeGen#171]
```
    public override void OnBeforeGeneration(OnBeforeGenerationArgs args)
    {

        base.OnBeforeGeneration(args);
        Console.WriteLine("before generate!");

    }

    public override void OnAfterGeneration(OnAfterGenerationArgs args)
    {
        base.OnAfterGeneration(args);
        Console.WriteLine("after generate");
    }
```

after generation does not write to the console:

Basically we need a way for the generation to finish. we then can copy all the typescript files and place it in our front end without manually doing this. For now i'm doing this with a .csx file

**Comment by jburzynski** [comment]
I just added a test for checking the order of calling the callbacks from generation specs, and it passes (`OnBeforeGeneration` is invoked first, then `OnBeforeBarrelGeneration` and `OnAfterGeneration`). You can check it in [`src/TypeGen/TypeGen.Core.Test/Generator/GeneratorTest.cs`](https://github.com/jburzynski/TypeGen/blob/master/src/TypeGen/TypeGen.Core.Test/Generator/GeneratorTest.cs).

I also tried it using the CLI and it did print "OnAfterGeneration" to the console, but it actually prints it before it prints the generated files, so e.g. something like this:

```
OnBeforeGeneration
OnBeforeBarrelGeneration
OnAfterGeneration

Generated a.ts
Generated a.ts
Generated a.ts

...

```

**Comment by jburzynski** [comment]
I just added a test for checking the order of calling these callbacks from generation specs, and it passes (`OnBeforeGeneration` is invoked first, then `OnBeforeBarrelGeneration` and `OnAfterGeneration`). You can check it in [`src/TypeGen/TypeGen.Core.Test/Generator/GeneratorTest.cs`](https://github.com/jburzynski/TypeGen/blob/master/src/TypeGen/TypeGen.Core.Test/Generator/GeneratorTest.cs).

I also tried it using the CLI and it did print "OnAfterGeneration" to the console, but it actually prints it before it prints the generated files, so e.g. something like this:

```
OnBeforeGeneration
OnBeforeBarrelGeneration
OnAfterGeneration

Generated a.ts
Generated b.ts
Generated c.ts

(...)

Files for project "(...)\src\TypeGen\TypeGen.Core.Test" generated successfully.
```

You can double-check if "after generate" was printed before the list of the generated files.
Other than that I'm not sure what might be causing it.

**Comment by stealthAngel** [comment]
I'll try to reproduce it when i have time
