### ISSUE TITLE
Generate one file containing all generated typescript interfaces

### ISSUE THREAD

**Issue by dgxhubbard** [jburzynski/TypeGen#18]
This is a feature request. Can you add a generation option that puts all typescript generated interfaces into a single file.

**Comment by jburzynski** [comment]
Thanks for taking time to comment on TypeGen!

The main idea of this project is to allow for single-class-per-file generation. If you want to generate all typescript interfaces to a single file, there exist other tools that let you do just that. For example, have you checked [TypeLITE](http://type.litesolutions.net/)? Or in general, any of the tools mentioned in [this StackOverflow question](https://stackoverflow.com/questions/16656406/dto-to-typescript-generator)? They may be more suitable for the task you need.

Please let me know if this solves your issue.

**Comment by jburzynski** [comment]
Closed due to inactivity.
