### ISSUE TITLE
No files being generated after migrating from TypeGen 4.1.1 on a .NET 4.8 project to TypeGen 5.0.1 on a .NET 8 project

### ISSUE THREAD

**Issue by hharvey84** [jburzynski/TypeGen#209]
Hopefully I include all the necessary details here. I am working on migrating an application from .NET 4.8 to .NET 8, and one of the steps I need to take is setting up TypeGen in the new project.  I have a web application project running .NET 4.8 containing a tgconfig.json file, and the assembly it referenced contained all of my Entity Framework 6 models, as well as a significant number of hand-generated POCO classes that all had ExportTsInterface attributes and were being generated successfully using TypeGen 4.1.1.

Today, I began trying to set this up in the .NET 8 version of my web app, which has a corresponding .NET 8 version of the model project to go along with it.  The models are generated using EF Core Power Tools, with the TypeGen attributes all added in automatically via a T4 template.  It builds successfully, and everything looks correct on inspection.  I did have to make some minor changes to the tgconfig.json file in the .NET 8 project (for some reason, I had to fully qualify my Converters with the assembly path or it couldn't find them), but nothing big.

Now, the `typegen generate` command runs without errors, but this is all I get:
```
Generating files for project "<ProjectName>"...
Files for project "<ProjectName>" generated successfully.
```

I have hundreds of files to generate, so for it to finish immediately and not generate any files is unexpected.  Am I missing something, based on my rundown?  I did make sure to build my solution before I ran TypeGen, because I have a tendency to forget that, but nothing changes.

**Comment by hharvey84** [comment]
Some additional info: I attempted using a GenerationSpec, but for some reason I am receiving this error:

```
GENERIC ERROR: Unable to cast object of type '<Namespace>.MyGenerationSpec' to type 'TypeGen.Core.SpecGeneration.GenerationSpec'.
```

**Comment by jburzynski** [comment]
This may happen if the old .NET 4.8 assembly is still in the `bin` folder. TypeGen just searches for the first dll or exe that matches the project name - maybe this can be improved in the future so that it tries to find the correct one.

**Comment by jburzynski** [comment]
You can also try if it helps to clear the NuGet cache: `nuget locals -clear all`
