### ISSUE TITLE
GENERIC ERROR: Value cannot be null.

### ISSUE THREAD

**Issue by raskolnikoov** [jburzynski/TypeGen#22]
I can't get this to work. Im using VS 2017 and TypeGen 1.6.1 on .NET v461

Here is the PM output I get.

`PM> TypeGen TypeGenDemo

Generating files for project "TypeGenDemo"...

GENERIC ERROR: Value cannot be null.

Parameter name: path2

   at System.IO.Path.Combine(String path1, String path2)

   at TypeGen.Cli.Program.Generate(String projectFolder, String configPath, Boolean verbose)

   at TypeGen.Cli.Program.Main(String[] args)

PM>`

**Comment by jburzynski** [comment]
Yeah I think pull request #21 fixes it. This will be included in the next release (1.6.2), which I will probably do today. In the meantime, you can use [this nupkg from the `dev` branch](https://github.com/jburzynski/TypeGen/blob/dev/nuget/TypeGen.1.6.2.nupkg), which contains this fix.

**Comment by raskolnikoov** [comment]
Great thanks!

**Comment by jburzynski** [comment]
Should be fixed now. Just released version 1.6.2.

**Comment by jburzynski** [comment]
Closed due to inactivity.
