### ISSUE TITLE
TsCustomBaseAttribute doesn't generate 'import-part'

### ISSUE THREAD

**Issue by jburzynski** [jburzynski/TypeGen#23]
_From @salmin89 on June 21, 2018 8:58_

**SomeClass.cs**
```
using TypeGen.Core.TypeAnnotations;

namespace MyProject.Types
{
    [TsIgnoreBase]
    [TsCustomBase("CustomBase")]
    [ExportTsInterface]
    public class SomeClass: CustomBase{ }
}
```

**CustomBase.cs**

```
using TypeGen.Core.TypeAnnotations;

namespace MyProject.Types
{
    [ExportTsInterface]
    public class CustomBase
    {
        public string name { get; set; }
        public string url { get; set; }
        [TsOptional]
        public string thumbnail { get; set; }
    }
}
```

**SomeClass.ts**

```
/**
 * This is a TypeGen auto-generated file.
 * Any changes made to this file can be lost when this file is regenerated.
 */

export interface SomeClass extends CustomBase{

}
```

I'm missing `import { CustomBase} from "./CustomBase";` from SomeClass.ts

_Copied from original issue: jburzynski/TypeGenDocs#1_

**Comment by jburzynski** [comment]
If you use custom base, there is no import, because only the name of the custom base is known (i.e. if the custom base is in a file, location of this file cannot be determined). You can use [`<custom-head>`](http://typegen.readthedocs.io/en/latest/usingtypegen.html#preserving-parts-of-a-typescript-file) tag to write import for the base class/interface by hand.

Another solution (would require code change, so I could do it) would be to add a property to `CustomBaseAttribute` for specifying base class' file path (e.g. `CustomBaseAttribute.ImportPath`) - would that be helpful in your case?

**Comment by salmin89** [comment]
I run a script that deletes all my types before I generate new ones. Maybe it's not the best way to do it, but it just makes it easier when getting rid of old files.

I would prefer to be able to specify the base. Thank you!

**Comment by jburzynski** [comment]
I'll make next release in a couple of days and I'll add `ImportPath` to `CustomBaseAttribute`. I'll keep you updated on the progress in this issue.

**Comment by jburzynski** [comment]
I added this to 1.6.3 - you can check it out. Usage is pretty self-explanatory, but I also updated [docs](http://typegen.readthedocs.io/en/latest/usingtypegen.html#tscustombaseattribute) so you can check there.

**Comment by jburzynski** [comment]
closed due to inactivity
