### ISSUE TITLE
Relative import-path is not updated when using custom OutputDir

### ISSUE THREAD

**Issue by salmin89** [jburzynski/TypeGen#27]
Hi,

The import-path for any reference-classes is not following the structure. It will try to import it directly in the same folder /MySpecificFolder, no matter where the referenceClass is stored

```
[ExportTsInterface(OutputDir = "MySpecificFolder")]
public class MyTestClass
    {
        public List<ReferenceClass> ListOfThings{ get; set; }
    }
```

like this:
`import { ReferenceClass} from "./MyOtherClasses/ReferenceClass";`

The correct import would be ../ because we know that we are 1 level deep into "MySpecificFolder"

**Comment by jburzynski** [comment]
Hi, it looks like a bug that will be solved in version 1.6.5 (should be released quite soon).
Check if it works when you add a slash (or backslash) after directory name (`[ExportTsInterface(OutputDir = "MySpecificFolder/")]`). This should solve the problem until 1.6.5 is released.

**Comment by salmin89** [comment]
That solved the problem. Thank you!

**Comment by jburzynski** [comment]
Should work without slashes in 1.6.5.
