### ISSUE TITLE
Error in converting Data Type:  Guid - DateTimeOffset - TimeSpan in EF6 model

### ISSUE THREAD

**Issue by moh-hassan** [jburzynski/TypeGen#32]
I tried to convert EF6 model classes to type script.
I get error to the following data type:

- Guid
- DateTimeOffset
- TimeSpan

>Unhandled Exception: TypeGen.Core.CoreException: Generated type must be either a
 C# class or enum. Error when generating type System.DateTimeOffset; inside type: System.DateTimeOffset, in Model ....

Is there any mapping to these data types?
What can I do to successfully convert the EF6 to type script?

**Comment by jburzynski** [comment]
Hi, I think this can be fixed by annotating the properties with `TsTypeAttribute` e.g. like this:

```csharp
[TsType(TsType.String)]
public Guid MyGuid { get; set; }

or:

[TsType("MyCustomType")]
public Guid MyGuid { get; set; }
```

**Comment by moh-hassan** [comment]
Thanks for reply.
