### ISSUE TITLE
Attempts to install CLI tooling on mac are failing!

### ISSUE THREAD

**Issue by andycwk** [jburzynski/TypeGen#33]
Hi!

Not sure if this is user error or a limitation of the CLI package, but I'll ask anyway!

I'm struggling to install the CLI tooling in my mac .net core 2.1 (v2.1.401) development environment.

I ran the following command...
`dotnet tool install -g TypeGen.DotNetCli`

And was presented with the following output..

> error NU1212: Invalid project-package combination for TypeGen.DotNetCli 1.6.7. DotnetToolReference project style can only contain references of the DotnetTool type 
> The tool package could not be restored.
> Tool 'typegen.dotnetcli' failed to install. This failure may have been caused by:
> 
> * You are attempting to install a preview release and did not use the --version option to specify the version.
> * A package by this name was found, but it was not a .NET Core tool.
> * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
> * You mistyped the name of the tool.

Any thoughts or ideas??

**Comment by jburzynski** [comment]
Hi! Thanks for reporting this - this is definitely a bug.

I've checked that on my computer TypeGen.DotNetCli stopped working completely (even for per-project install) after I updated my nuget.exe to the newest version - so I'm going to read more about what can be a possible cause for this.

I'll post an update here when I manage to fix it, or just to let you know about the progress.

Cheers!

**Comment by jburzynski** [comment]
So according to this thread https://github.com/dotnet/cli/issues/9782 (Kathleen Dollard's answer), the currently existing **per-project tools** will be dropped in the future in favour of **repo tools** (currently in development), which will resemble currently available **global tools**.

For this reason, I decided to change TypeGen.DotNetCli to only be a global tool (i.e. per-project tool is dropped), which will in theory make it easier to be used as a repo tool in the future.

So now if you type `dotnet tool install -g TypeGen.DotNetCli`, it should work (it will install TypeGen.DotNetCli v. 2.0.0, which uses the latest TypeGen 1.6.7).

**Comment by jburzynski** [comment]
closed due to inactivity
