### ISSUE TITLE
Add option to clear output directory (feature request)

### ISSUE THREAD

**Issue by zarusz** [jburzynski/TypeGen#41]
Hi,

While using the TypeGen.DotNetCli I noticed the output directory leaves old TS models for classes C# that were already deleted. Is it possible to add an option to the `tgconfig.json` to remove all files in output dir prior TS model generation?

Without that, we might keep on aggregating old TS models when people forget to remove them.

Thanks,

**Comment by jburzynski** [comment]
Hi,

yes, TypeGen doesn't clear the directory. I'll add this functionality to backlog and release it in a future release.

In the meantime I guess chaining `rm -r [dir]` with `dotnet typegen generate` should probably work even in pre/post build events.

Cheers

**Comment by zarusz** [comment]
Hey,

Yes, the `rm -r` is what I've been thinking too, but having that in the tool would be more awesome.

Thanks!

**Comment by jburzynski** [comment]
Yes, definitely, it will be in a future release.
Cheers

**Comment by jburzynski** [comment]
I just released version 2.1.1, which adds the functionality to clear the output directory before generating new files. Seems to be working fine, but let me know in case of any problems.

**Comment by zarusz** [comment]
I just upgraded to 2.1.2, enabled the `"clearOutputDirectory": true` in `tgconfig.json` and it worked smooth 👍 

One small suggestion is to maybe log the fact the directory is being cleaned in the build output. This might help folks reinforce that this option is actually enabled.

Once again, thanks!

**Comment by jburzynski** [comment]
This might be worth adding in a future version. Glad it works! Thanks
