### ISSUE TITLE
StackOverflowException

### ISSUE THREAD

**Issue by ryanbuening** [jburzynski/TypeGen#43]
I have TypeGen 2.1.1 package installed and am using version 2.1.1 of the CLI.

I created the GenerationSpec below and added it to the root of my project.

```
    public class MyGenerationSpec : GenerationSpec
    {
        public MyGenerationSpec()
        {
            AddEnum<FarmDTOs.Loss.Causes>();
        }
    }
```

FarmDTOs.Loss.Causes is an enum inside of a class which resides in a Nuget package:

```
namespace FarmDTOs
{
    public class Loss
    {
        public string Id;
        public DateTime Date;
        public Causes Cause;
        public int Amount;

        public Loss();

        public enum Causes
        {
            Unspecified = 0,
            Earthquake = 1,
            Fire = 2,
        }
    }
}
```

When I run `dotnet typegen generate` I get the following messages:

`Generating files for project "."...`
`Process is terminating due to StackOverflowException.`

Any ideas as to what would be causing this?

**Comment by jburzynski** [comment]
That looks strange. I'll try to replicate and I'll let you know here when I manage to make a fix. Is the enum the only thing you specify in `MyGenerationSpec`? Or maybe you also have something that uses `FarmDTOs.Loss` as a property type (or `FarmDTOs.Loss` itself) etc.?

**Comment by ryanbuening** [comment]
Yes. The enum was the only thing I had in `MyGenerationSpec`. I also tried `AddClass<FarmDTOs.Loss>();` and received the same error: `Process is terminating due to StackOverflowException.`

**Comment by jburzynski** [comment]
Turned out this error was due to a typo I made (facepalm)! I've uploaded TypeGen 2.1.2 and this should be fixed.

**Comment by jburzynski** [comment]
BTW, I haven't tested TypeGen with nested types. If you're using GenerationSpec it should be fine, because you just list the types you want to be generated, but I'm not sure how it would work if there were attributes on nested types. I'll review how it works and make changes in the next release if necessary to make TypeGen work with nested types.

**Comment by ryanbuening** [comment]
Awesome. Thanks for the fix and info.
