### ISSUE TITLE
[Feature Request] Provide a way to change the boilerplate text

### ISSUE THREAD

**Issue by ryanbuening** [jburzynski/TypeGen#48]
It would be nice if there was a way to modify the boilerplate text that goes at the top of the generated TypeScript files. Either from the GenerationSpec or the `dotnet typegen generate` command.

My use case is that I want to provide a version number to all of my TypeScript files.

```
/**
 * This is a TypeGen auto-generated file.
 * Any changes made to this file can be lost when this file is regenerated.
 * **FooDTOs version 3**
 */
```

Great project by the way. Extremely useful.

**Comment by jburzynski** [comment]
Glad it's helpful!

I've added an option to version 2.1.3 (just published). You can add `fileHeading` to tgconfig.json and just type in the string that should be at the beginning of a TS file.

Also, by default it has no "new line" signs at the end, so if you need some spacing, you can add new line signs at the end of the string.

**Comment by ryanbuening** [comment]
Awesome. Thanks!
