### ISSUE TITLE
singleQuotes doesn't affect enum

### ISSUE THREAD

**Issue by Sushi21** [jburzynski/TypeGen#57]
Hi,

We are trying to generate typescript enums with the string single quotes.

TGConfig get these to values.

  "enumStringInitializers": true,
  "singleQuotes": true,

But it is still generating enums with double quotes

**Comment by Sushi21** [comment]
we can create a pull request for that

**Comment by jburzynski** [comment]
Hi,

thanks for your offer to create a pull request, I appreciate this.

Fortunately it turned out to be a quick fix, so I just released version 2.3.2 which contains this fix.

**Comment by jburzynski** [comment]
closed due to inactivity

**Comment by Sushi21** [comment]
Awesome Thanks
