### ISSUE TITLE
How to add custom static property to class?

### ISSUE THREAD

**Issue by lhysrc** [jburzynski/TypeGen#60]
Is there a way to add some static properties to the typescript class, like assembly info.
Like this:
```typescript
export class OrgViewModel {
    /** Id */
    id? : string;
    /** Path */
    path? : string;

    static readonly _className = "Admin.ViewModels.OrgViewModel";
    static readonly _assemblyName = "Admin.ViewModels";
}
```

**Comment by jburzynski** [comment]
One option would be to add corresponding static readonly fields to a C# class like this (then they get automatically generated to TypeScript):

```csharp
class OrgViewModel
{
  public static readonly _className = "Admin.ViewModels.OrgViewModel";
  public static readonly _assemblyName = "Admin.ViewModels";
}
```

Another thing that comes to my mind is that you could define `customBody` in the TypeScript file itself like this:

```typescript
export class OrgViewModel {
    /** Id */
    id? : string;
    /** Path */
    path? : string;

    //<custom-body>
    static readonly _className = "Admin.ViewModels.OrgViewModel";
    static readonly _assemblyName = "Admin.ViewModels";
    //</custom-body>
}
```

Anything between `custom-body` or `custom-head` tags is preserved when a TypeScript file is generated.

**Comment by lhysrc** [comment]
Sorry, I did not say it clearly.
I mean to dynamically get the information of the C# class and add them to the TS class.

**Comment by jburzynski** [comment]
If you need to add these properties to every class, I think these is no solution right now that would allow for this (or at least I can't think of any).

For a single class, something like this should work (the same as the solution from my previous post, only with dynamically generated values):

```csharp
class OrgViewModel
{
  public static readonly _className = typeof(OrgViewModel).FullName;
  public static readonly _assemblyName = typeof(OrgViewModel).GetTypeInfo().Assembly...GetName or something like that;
}
```

**Comment by jburzynski** [comment]
Closed due to inactivity
