### ISSUE TITLE
Duplicate class names not supported

### ISSUE THREAD

**Issue by draape** [jburzynski/TypeGen#62]
I would like to generate ts interfaces based on my existing models, but because they have the same name, only one interface is generated. My structure looks a bit like this:

```c#
public class GetFoo {
    public class Query<Response> {
        public string SomeProperty { get; set; }
    }

    public class Response {
        public string PropertyA { get; set; }
    }
}

public class GetBar {
    public class Query<Response> {
        public string SomeProperty { get; set; }
    }

    public class Response {
        public string PropertyB { get; set; }
    }
}
```

I am able to manipulate the type name with a type name converter and get the interfaces `GetFooQuery`, `GetBarQuery`, `GetFooResponse` and `GetBarResponse`, but the file name converter does not have any knowledge of the type which means I only get one Query.ts and one Response.ts file.

If I had access to the type in the name converter, or if I could apply the type converter before the name converter I guess it might work. It's currently not possible as far as I can see from the docs, maybe there is some other solution that I haven't come across?

**Comment by jburzynski** [comment]
I think file name converters are TypeNameConverters, so your idea should be possible (in [`GeneratorOptions`](https://github.com/jburzynski/TypeGen/blob/master/src/TypeGen/TypeGen.Core/GeneratorOptions.cs), `FileNameConverters` are of type `TypeNameConverterCollection`).

If you try to provide a TypeNameConverter to the `fileNameConverters` CLI parameter, does it throw any error?

I wrote a tutorial in the docs on [how to discriminate file names based on the type](https://typegen.readthedocs.io/en/latest/converters.html#type-name-converter), so if this is not working, it would be a major bug :)

**Comment by draape** [comment]
Awesome! I didn't catch that inheritance detail. Works great with just re-using the same type name converter in the `fileNameConverters` property in tgconfig. Thanks!

**Comment by jburzynski** [comment]
Glad I could help!
