### ISSUE TITLE
ExportTsInterface from C# interface

### ISSUE THREAD

**Issue by aleks-angelov** [jburzynski/TypeGen#63]
How do I generate a TypeScript interface from a C# interface? When I use the [ExportTsInterface] attribute on a public interface, I get a build-time error: "Attribute 'ExportTsInterface' is not valid on this declaration type. It is only valid on 'class' declarations.".

**Comment by jburzynski** [comment]
Hi, it's not possible at the moment.
TypeGen was mainly designed to generate DTO (or other simple) classes into TypeScript, so C# interfaces are not processed.

Do you need to generate properties from C# interfaces?

**Comment by aleks-angelov** [comment]
@jburzynski Yes, I would like to generate the properties of C# interfaces.

**Comment by jburzynski** [comment]
I added this functionality to the "todo" list, so I'll try to add it in the next release.

However, currently I'm not having enough free time to work on TypeGen, and this will most likely continue for a while, so this means I will not be able to implement any new functionality in the near future.

The thing I could do is merge pull requests and make releases from what's been implemented.

You could look up other PRs to find out which files should most likely be changed.

Sorry for this, but I just currently don't have time right now unfortunately. I'll implement any new functionality as soon as I have an opportunity to do so.

**Comment by jburzynski** [comment]
This is possible now in version 2.4.0. There is no support for interface inheritance yet though - I'll aim to implement it in some future release.
