### ISSUE TITLE
Tab indentation in generated files

### ISSUE THREAD

**Issue by aleks-angelov** [jburzynski/TypeGen#64]
Is it possible for the generated files to have tab indentation instead of space indentation? I read about the "tabLength" configuration option in the documentation, but I could not find anything about switching indentation modes.

**Comment by jburzynski** [comment]
This is currently not possible.
As I explained in issue #63 , unfortunately I won't be able to implement it in the nearest future.

But I can merge PRs and make releases.

Cheers

**Comment by jburzynski** [comment]
This is possible now in version 2.4.0 (you can use the `useTabCharacter` option).
