### ISSUE TITLE
Add support for overwritten names from JSON.NET

### ISSUE THREAD

**Issue by PerfectlyNormal** [jburzynski/TypeGen#66]
We're using TypeGen to generate TypeScript models for an ASP.NET Core API, consumed by an Angular app. One of the models we have are sourced from an external API which returns JSON in a different format than we prefer, so I use `JsonProperty` from JSON.NET to customize the names. This is not detected by TypeGen, so I get a model with the wrong names.

Example:

```csharp
public class ApplicableMeasureRow
{
    public int Id { get; private set; }
    [JsonProperty("goods_NOM_ITEM_ID")]
    public string GoodsNomenclatureItemId { get; private set; }
}
```

generates the TypeScript:

```typescript
export class ApplicableMeasureRow {
  public id: number = undefined;
  public goodsNomenclatureItemId: string = undefined;
}
```

but the API serializes and sends it as `goods_NOM_ITEM_ID`, so my TypeScript code doesn't work.

I know it's possible to remap the properties in TypeGen, but that requires duplicate attributes, and since JSON.NET is so common, it would be nice if TypeGen could find that attribute and handle it automatically.

**Comment by jburzynski** [comment]
I replaced `INameConverter` with `IMemberNameConverter` in version 2.4.1 (just released), which gives the possibility to convert member names depending on the member's `MemberInfo`.

So to use the property name from `JsonPropertyAttribute`, you could add a custom converter as the first converter in the chain (`propertyNameConverters` config parameter):

```csharp
public class JsonMemberNameConverter : IMemberNameConverter
{
    public string Convert(string name, MemberInfo memberInfo)
    {
        var attribute = memberInfo.GetCustomAttribute<JsonPropertyAttribute>();
        return attribute != null ? attribute.PropertyName : name;
    }
}
```

**Comment by PerfectlyNormal** [comment]
Great! I guess I'll have to get around to upgrading then. Thanks a lot for your work 👍

**Comment by ulmer-morozov** [comment]
For those who are using System.Text.Json.Serialization.
You can use similar code:
