### ISSUE TITLE
Folders with periods being treated as an extension for barrel generation

### ISSUE THREAD

**Issue by NewDark90** [jburzynski/TypeGen#72]
This is somewhat of an edge case bug, but it does affect my implementation and I figure I should bring this up. Directories that include periods will have the last section lopped off. 
https://github.com/jburzynski/TypeGen/blob/150734e32b7c7427a72c8982f8de2b754db4fcf4/src/TypeGen/TypeGen.Core/Generator/Generator.cs#L211

**Comment by jburzynski** [comment]
This definitely needs fixing, thanks for reporting! I'll aim to fix it this weekend, you're also always very welcome to make a pull request if you feel like doing one!

**Comment by NewDark90** [comment]
PR is up. :)

**Comment by jburzynski** [comment]
This should be now fixed in 2.4.3. Please let me know if it works / doesn't work :)
