### ISSUE TITLE
ToTitleCase string extension wrong behaviour with single PascalCase member

### ISSUE THREAD

**Issue by fabiomaistro** [jburzynski/TypeGen#77]
When using ToTitleCase (e.g. in the UnderscoreToPascalCaseConverter) string extension, the function behaves incorrectly when dealing with a single word in PascalCase.
Example:
**Source:** "LimitedCompany"
**Expected:** "LimitedCompany"
**Result:** "Limitedcompany"

In this scenario, the resulting string should not be affected by the function...

**Comment by jburzynski** [comment]
I merged the PR and released it in 2.4.4 - please let me know if something doesn't work.
