### ISSUE TITLE
Missing command line help

### ISSUE THREAD

**Issue by vsvirydau-cl** [jburzynski/TypeGen#82]
Currently running `dotnet typegen` only produces output that looks like `TypeGen v<VERSION>`.

It would be nice if some help information was provided for commands, and command line options.

**Comment by jburzynski** [comment]
Thanks for pointing this out. This actually used to show up, but I made a bad refactoring and it stopped working. I released a new version 2.4.6 and the full help should be showing now.

**Comment by vsvirydau-cl** [comment]
Works now, thanks.
