### ISSUE TITLE
tslint " should be ' (quotemark)

### ISSUE THREAD

**Issue by SlayerSvamp** [jburzynski/TypeGen#83]
when generating a class with a reference to another generated object, the generated code reads:

```
import { MyEnum } from "./my-enum";

export class MyClass {
    myEnum: MyEnum;
    ...
}
```

tslint has an issue with the double quotation marks, saying __tslint " should be ' (quotemark)__

**Comment by jburzynski** [comment]
Hi, if you'd like to use single quotes instead of double quotes, you can use the singleQuotes configuration parameter in tgconfig.json . Hope this solves your problem!

**Comment by SlayerSvamp** [comment]
@jburzynski thanks! That was exactly what I was looking for :)
