### ISSUE TITLE
Generated interface files do not import dependencies

### ISSUE THREAD

**Issue by vsvirydau-cl** [jburzynski/TypeGen#84]
TL;DR
=====
* If `[ExportTs*]` targets a `class` - imports are specified correctly
* If `[ExportTs*]` targets an `interface` - imports are omitted

Problem
=======

I have something like this

```
# ISomeInterface.cs
[ExportTsInterface]
public interface ISomeInterface {
    IList<IOtherInterface> Others { get; set; }
}

# IOtherInterface.cs
[ExportTsInterface]
public interface IOtherInterface {

}
```

Generated files:

```
# i-some-interface.ts
# there's no "import { IOtherInterface } from './i-other-interface.ts';" here
export interface ISomeInterface {
   others: IOtherInterface[];
}
```

Typescript compiler now gives me an error
```
ERROR in src/i-some-interface.ts(12,17): error TS2304: Cannot find name 'IOtherInterface'
```

If I use `[ExportTsInterface]` on a class instead, `*.ts` files now correctly have `import { IOtherInterface } from ...` in them.

Environment
============
Nuget:
`<PackageReference Include="TypeGen" Version="2.4.7" />`
Tool:
```
"dotnet-typegen": {
      "version": "2.4.7",
      "commands": [
        "dotnet-typegen"
      ]
    }
```
`tgconfig`:
```
{
  "assemblies": [
    "src/web/bin/Release/netcoreapp3.0/web.dll",
    "src/web/bin/Release/netcoreapp3.0/core.dll",
    "src/web/bin/Release/netcoreapp3.0/infrastructure.dll"
  ],
  "clearOutputDirectory": true,
  "outputPath": "src/front-end/src/models",
  "createIndexFile": true,
  "enumStringInitializersConverters": [],
  "customTypeMappings": {
    "NodaTime.Instant": "Date"
  }
}
```

**Comment by vsvirydau-cl** [comment]
https://gist.github.com/vsvirydau-cl/2a747c1aea524c5530dfdfeabd043229 link to a repro

**Comment by jburzynski** [comment]
Thanks for reporting this and much thanks for the pull request! :) I'll look into it and check out the PR over the weekend, this week I won't have time to look at it sooner unfortunately, hope it's ok!

**Comment by vsvirydau-cl** [comment]
Should be fine, I can work out some fix in the interim...
If this was an `npm` package I'd just point to my github fork, not sure how to do that with nuget...

**Comment by vsvirydau-cl** [comment]
Ok, dotnet core sucks for custom nuget sources right now, so I ended up compiling patched version and bundling it with the build for now...

**Comment by jburzynski** [comment]
Hey, this is just an update that although I haven't released the fix, I do keep this issue in mind and I'll fix it whenever I have a moment for it.

**Comment by jburzynski** [comment]
I just uploaded version 2.4.8 (it includes the PR), please let me know if it works, thanks.

**Comment by vsvirydau-cl** [comment]
Looks like it works fine. Thanks.
