### ISSUE TITLE
C# byte?[] property causes APPLICATION ERROR: Generated type must be either a C# class or enum

### ISSUE THREAD

**Issue by bigbadwolf88888** [jburzynski/TypeGen#92]
TypeGen throws the error:

"APPLICATION ERROR: Generated type must be either a C# class or enum. Error when generating type System.Nullable`1"

When a C# class contains a byte?[] property type like:

public byte?[] Password { get; set; }

**Comment by jburzynski** [comment]
Hi, sorry for the quite late response.

I think that potentially a workaround for this would be possible when using generation specs.
I guess it should be possible to get all property/field names for a type using reflection and then for each member do `.Member(memberName).Type(someType)` if the member is nullable (and then wrap the logic in some extension method etc.).
This is only a general idea; I haven't tried it and I'm not 100% sure if it's easily possible.

In terms of fixing the issue, I could do it at some point whenever I find a moment (which can take some time) or I could merge the PR if you'd be interested in creating one (which can also take some time, but less than me fixing the issue).

If you need to create a NuGet package to use locally, you can do it by running the 3 scripts in the root of the project:

- version-update [old version, e.g. 2.4.0] [new version, e.g. 2.4.1]
- build-publish
- nuget-update

**Comment by jburzynski** [comment]
Should be fixed in 4.3.0.
