### ISSUE TITLE
Newtonsoft.Json dependency lower than 12.02

### ISSUE THREAD

**Issue by brettveenstra** [jburzynski/TypeGen#94]
Firstly, kudos on project idea, site with docs, changelog, API references, examples... really nice work!

Trying it out in existing solution with Azure Functions and bumping into the Newtonsoft.Json >= 12.02 dependency requirement.

Does your code really need a version this current, or would 11.0.1 (2018), or even 10.0.3 (2017) work out?  Just looking to broaden the options and age of platforms where could be using this.

**Comment by jburzynski** [comment]
Hi, thanks, I'm glad you like it!

I think I've decided to use the newest (at that time) version of Newtonsoft.Json to potentially get all the newest functionality - there may have been other reasons, but I don't remember exactly.

So far TypeGen is only using the basic JSON serialize/deserialize functionality (which was probably included in the first versions of Newtonsoft.Json), so I think an assembly redirect to a lower version of Newtonsoft.Json should work (I'm not sure if you've already tried it or have the possibility to do this).

If you try this (or already tried this), can you please let me know if it works? Thanks

**Comment by jburzynski** [comment]
Closed due to inactivity
