### ISSUE TITLE
Error when Assembly name is different from project name

### ISSUE THREAD

**Issue by Allov** [jburzynski/TypeGen#97]
When the specified Assembly name is different than the project name, the tool crash with an error trying to find `ProjectName.dll` or `ProjectName.exe`. Perhaps it should look at the `csproj` configuration for assemble name?

**Comment by jburzynski** [comment]
Thanks for reporting this issue.

Looking at the csproj configuration would be more reliable, thanks for suggesting that - I've added a task to implement this in the [todo](https://trello.com/b/ykSEU8Ef/todo) list.

To override the default assembly name/location (or to specify additional assemblies to use), you can use the `assemblies` parameter in `tgconfig.json`. More information on how to use it is [in the docs](https://typegen.readthedocs.io/en/latest/cli.html#configuration-file).

Please let me know if this solves the problem.

**Comment by Allov** [comment]
Well, maybe I should open a new ticket (or perhaps you guys have a slack I could join to ask questions), but I can't get the tool to work with a configuration. Either with a `tsconfig.json` or `GenerationSpec`.

I'm using the nuget package installed in my project which is a Standard 2.0 library.

**Comment by Allov** [comment]
Never mind that. I had to specified the configuration path in the command line tool! Yay! it works great!

**Comment by jburzynski** [comment]
Great, I'm glad it worked!
