### ISSUE TITLE
Dto with interfaces has no implements

### ISSUE THREAD

**Issue by Allov** [jburzynski/TypeGen#98]
So, here's an example:

```
    public interface ICard
    {
         string Title { get; set; }
         string Description { get; set;
    }
```
Which has a final DTO of this form:

```
    public class Card : ICard
    {
         string Title { get; set; }
         string Description { get; set;
    }
```

The final output using typegen is:

```
/**
 * This is a TypeGen auto-generated file.
 * Any changes made to this file can be lost when this file is regenerated.
 */

export class ICard {
    title: string;
    description: string;
}
```

```
/**
 * This is a TypeGen auto-generated file.
 * Any changes made to this file can be lost when this file is regenerated.
 */

export class Card {
    title: string;
    description: string;
}
```

I was expected to have this instead:
```
/**
 * This is a TypeGen auto-generated file.
 * Any changes made to this file can be lost when this file is regenerated.
 */

import { ICard} from "./i-card";

export class Card implements ICard {
    title: string;
    description: string;
}
```

Is there any way to achieve this right now?

**Comment by jburzynski** [comment]
Could you paste the tgconfig.json and (if you're using one) the generation spec? I don't remember if I've added handling of interface inheritance, so I'm not sure if it's an issue with the tool or the configuration.

Thanks

**Comment by Allov** [comment]
Can confirm, only supporting extends: https://github.com/jburzynski/TypeGen/blob/master/src/TypeGen/TypeGen.Core/Templates/Class.tpl

I'm working on a PR, just need to figure out imports.

**Comment by taylorjp** [comment]
I'm running into this issue as well with inherited interfaces.  I want to pass around the lowest level interface in typescript, but I can't because it actually doesn't have all the properties.

Example C# interfaces:
```
public interface IAggregateDto : ICalculationDto
{
    int AggregationType { get; set; }
}

public interface ICalculationDto
{
    string name { get; set; }
}
```

and the generated Typescript code:
```
export interface IAggregateDto {
    int AggregationType: number;
}

export interface ICalculationDto {
    name: string;
}
```

**Comment by taylorjp** [comment]
Any chance this could be merged soon?  Would love to migrate to TypeGen completely from TypeLite, but this is preventing it.  Thanks!

**Comment by jburzynski** [comment]
Lately I haven't had much time for TypeGen and also I need some time away from the project, so I won't be doing too much in the near future.

I've created 3 scripts that you can use to create your own NuGet packages (there's a link to a guide on how to use them in the main readme file). So you could merge this pr in your own fork and then create the NuGet packages to use in a custom NuGet feed.

**Comment by rdsimes** [comment]
Sorry to hear you've retired this project! 
looks like the PR implementing this has been merged so all that's needed would be the latest version to be published - i've built a local version which works well but would be amazing if this could be published to nuget

**Comment by jburzynski** [comment]
Yes, it looks like it was merged - I don't remember exactly to which version it was added, but should already be in the current version.
